# Generated by Django 4.2.1 on 2023-06-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medmoeapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medikament',
            name='einnahme',
        ),
        migrations.RemoveField(
            model_name='medikament',
            name='letze_bestellung',
        ),
        migrations.RemoveField(
            model_name='ueberweisung',
            name='termin',
        ),
        migrations.AddField(
            model_name='ueberweisung',
            name='kontakt',
            field=models.ForeignKey(blank=True, default='Thomas', on_delete=django.db.models.deletion.CASCADE, to='medmoeapp1.kontakt', verbose_name='Kontakt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='arzt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ArztB', to='medmoeapp1.kontakt', verbose_name='Arzt'),
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='kunde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='KundeB', to='medmoeapp1.kontakt', verbose_name='Kunde'),
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wann', models.DateTimeField(verbose_name='Wann')),
                ('bemerkung', models.CharField(max_length=100, verbose_name='Bemerkung')),
                ('wer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KundeT', to='medmoeapp1.kontakt', verbose_name='Wer')),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArztT', to='medmoeapp1.kontakt', verbose_name='Bei wem')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['-wann'],
            },
        ),
    ]
