# Generated by Django 4.2.1 on 2023-06-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medmoeapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontakt',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakte'},
        ),
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('bestell_datum', models.DateField(auto_now_add=True, verbose_name='Bestelldatum')),
                ('bemerkung', models.TextField(verbose_name='Bemerkung')),
                ('arzt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Arzt', to='medmoeapp1.kontakt', verbose_name='Arzt')),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Kunde', to='medmoeapp1.kontakt', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-bestell_datum'],
            },
        ),
    ]
