# Generated by Django 4.2.1 on 2023-06-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmoeapp1', '0002_alter_kontakt_options_bestellung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='bemerkung',
            field=models.TextField(blank=True, verbose_name='Bemerkung'),
        ),
    ]
