# Generated by Django 4.2.1 on 2023-06-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medmoeapp1', '0002_remove_medikament_einnahme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ueberweisung',
            options={'verbose_name': 'Überweisung', 'verbose_name_plural': 'Überweisungen'},
        ),
        migrations.AlterField(
            model_name='ueberweisung',
            name='kontakt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medmoeapp1.kontakt', verbose_name='Kontakt'),
        ),
    ]
