# Generated by Django 4.2.1 on 2023-06-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medmoeapp1', '0004_bestellung_medikamente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medikament',
            name='letzte_lieferung',
        ),
    ]
