# Generated by Django 4.2.1 on 2023-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmoeapp1', '0005_remove_medikament_letzte_lieferung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ueberweisung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('details', models.CharField(max_length=100, verbose_name='Details')),
                ('termin', models.DateTimeField(verbose_name='Termin')),
            ],
            options={
                'verbose_name': 'Ueberweisung',
                'verbose_name_plural': 'Ueberweisungen',
            },
        ),
        migrations.AddField(
            model_name='bestellung',
            name='ueberweisung',
            field=models.ManyToManyField(to='medmoeapp1.ueberweisung', verbose_name='Überweisungen'),
        ),
    ]
