# Generated by Django 4.2.1 on 2023-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmoeapp1', '0006_ueberweisung_bestellung_ueberweisung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='medikamente',
            field=models.ManyToManyField(blank=True, to='medmoeapp1.medikament', verbose_name='Medikamente'),
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='ueberweisung',
            field=models.ManyToManyField(blank=True, to='medmoeapp1.ueberweisung', verbose_name='Überweisungen'),
        ),
    ]
