# Generated by Django 4.2.1 on 2023-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmoeapp1', '0007_alter_bestellung_medikamente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medikament',
            name='beschreibung',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
    ]
